### ISSUE TITLE
NPE crash while trying to observe/sync an `OnlineRepository`

### ISSUE THREAD

**Issue by levibostian** [levibostian/Driver-Android#23]
Teller version: `9883a8c23b` (commit on dispose branch)

## Description: 

With an app I am building, I got a crash using Teller. The stacktrace is below. My guess is that I call `sync` before I call `observe` and then call `observe` while the API network call is going on? This is my only idea at this time looking through the [OnlineRepository code that initializes the state of data](https://github.com/levibostian/Teller-Android/blob/dispose/teller/src/main/java/com/levibostian/teller/repository/OnlineRepository.kt#L104-L105)

Stacktrace:

```
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property dataState has not been initialized
        at com.levibostian.teller.subject.OnlineDataStateBehaviorSubject.onNextDoneFirstFetch(OnlineDataStateBehaviorSubject.kt:77)
        at com.levibostian.teller.repository.OnlineRepository$beginObservingStateOfData$$inlined$let$lambda$2.invoke(OnlineRepository.kt:89)
        at com.levibostian.teller.repository.OnlineRepository$beginObservingStateOfData$$inlined$let$lambda$2.invoke(OnlineRepository.kt:15)
        at com.levibostian.teller.repository.OnlineRepository$_sync$1.accept(OnlineRepository.kt:151)
        at com.levibostian.teller.repository.OnlineRepository$_sync$1.accept(OnlineRepository.kt:15)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64) 
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111) 
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onComplete(ObservableSubscribeOn.java:68) 
        at retrofit2.adapter.rxjava2.ResultObservable$ResultObserver.onComplete(ResultObservable.java:68) 
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) 
        at io.reactivex.Observable.subscribe(Observable.java:12025) 
        at retrofit2.adapter.rxjava2.ResultObservable.subscribeActual(ResultObservable.java:34) 
        at io.reactivex.Observable.subscribe(Observable.java:12025) 
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by levibostian** [comment]
At this time, I will avoid dealing with this bug because I will be making big changes to the code base anyway. I have made some big changes to the Teller-iOS lib's API and will be making the same changes to this project. 

After the API updates are done, the code that caused this bug will be removed/changed anyway.
