### ISSUE TITLE
[BUG] Crash because node 

### ISSUE THREAD

**Issue by levibostian** [levibostian/Driver-Android#63]
Version: `0.2.0-alpha`

New crash from Crashlytics:

```
Caused by c.f.b.b.b.a.g$b: Node not possible path in state machine with current state of machine: State: Cache response does not exist, but it is being fetched for first time.  
       at com.levibostian.teller.cachestate.online.statemachine.OnlineCacheStateStateMachine.cache(OnlineCacheStateStateMachine.java:168)
       at com.levibostian.teller.repository.OnlineRepository$restartObservingCache$1$1$2.invoke(OnlineRepository.java:166)
       at com.levibostian.teller.repository.OnlineRepository$restartObservingCache$1$1$2.invoke(OnlineRepository.java:41)
       at com.levibostian.teller.subject.OnlineCacheStateBehaviorSubject.changeState(OnlineCacheStateBehaviorSubject.java:62)
       at com.levibostian.teller.repository.OnlineRepository$restartObservingCache$1$1.accept(OnlineRepository.java:166)
       at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

Nothing to say here except that the crash happened after Teller successfully completed a fetch call. 

I am guessing this closely resembles [this ios issue](https://github.com/levibostian/Teller-iOS/issues/64).

**Comment by levibostian** [comment]
This has been fixed in iOS's Teller and has been working in production well with no crashes in my apps since the fix. [See pr](https://github.com/levibostian/Teller-iOS/pull/77/files#diff-9d61e9b9abbc4c512aefb1b525de7187R70-R82) for implementation.
